// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorPortal.Data;

#nullable disable

namespace VendorPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111201546_AddUserFirmaRelationshipfix")]
    partial class AddUserFirmaRelationshipfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Dokuman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BoyutKB")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaTipi")
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GecerlilikBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kategori")
                        .HasColumnType("integer");

                    b.Property<string>("Versiyon")
                        .HasColumnType("text");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("YukleyenUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("YukleyenUserId");

                    b.ToTable("Dokumanlar");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Firma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("FirmaTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.Property<string>("WebSitesi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("VergiNo")
                        .IsUnique();

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.FirmaIliskisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MusteriFirmaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TedarikciFirmaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MusteriFirmaId");

                    b.HasIndex("TedarikciFirmaId");

                    b.ToTable("FirmaIliskileri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Ihale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("GecerlilikSuresiGun")
                        .HasColumnType("integer");

                    b.Property<bool>("HerkeseAcikMi")
                        .HasColumnType("boolean");

                    b.Property<string>("IhaleAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IhaleTuru")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MusteriFirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferansNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TeklifBaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TeklifBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TumTedarikcilereAcikMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MusteriFirmaId");

                    b.HasIndex("ReferansNo")
                        .IsUnique();

                    b.ToTable("Ihaleler");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleDaveti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DavetTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IhaleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TedarikciFirmaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IhaleId");

                    b.HasIndex("TedarikciFirmaId");

                    b.ToTable("IhaleDavetleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleDokuman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("BoyutKB")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaTipi")
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IhaleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IhaleTeklifId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("YukleyenUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IhaleId");

                    b.HasIndex("IhaleTeklifId");

                    b.HasIndex("YukleyenUserId");

                    b.ToTable("IhaleDokumanlari");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IhaleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("IstenenMiktar")
                        .HasColumnType("numeric");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MalzemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spesifikasyon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IhaleId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("IhaleKalemleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleTeklif", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IhaleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TedarikciFirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeklifNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TeklifTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTeklifTutari")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IhaleId");

                    b.HasIndex("TedarikciFirmaId");

                    b.HasIndex("TeklifNo")
                        .IsUnique();

                    b.ToTable("IhaleTeklifleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleTeklifKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<Guid>("IhaleKalemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IhaleTeklifId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("IndirimOrani")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<decimal>("TeklifEdilenMiktar")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("TeslimSuresiGun")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IhaleKalemId");

                    b.HasIndex("IhaleTeklifId");

                    b.ToTable("IhaleTeklifKalemleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.MailBildirimi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliciEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("text");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferansId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReferansTipi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MailBildirimleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Malzeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirmaId");

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisBaslik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DokumanlarJson")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HedefTeslimatTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriFirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferansNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SiparisTuru")
                        .HasColumnType("integer");

                    b.Property<Guid>("TedarikciFirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeslimatAdresi")
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("MusteriFirmaId");

                    b.HasIndex("ReferansNo")
                        .IsUnique();

                    b.HasIndex("TedarikciFirmaId");

                    b.ToTable("SiparisBasliklar");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IstenenTeslimatTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MalzemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("OnaylananBirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OnaylananMiktar")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SiparisBaslikId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("SiparisBaslikId");

                    b.ToTable("SiparisKalemler");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisOnayGecmisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("EskiDurum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IslemTipi")
                        .HasColumnType("integer");

                    b.Property<Guid>("IslemYapanUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SiparisBaslikId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SiparisKalemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YeniDurum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IslemYapanUserId");

                    b.HasIndex("SiparisBaslikId");

                    b.HasIndex("SiparisKalemId");

                    b.ToTable("SiparisOnayGecmisleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.TedarikciMalzemeEslestirme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MusteriFirmaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusteriMalzemeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TedarikciFirmaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TedarikciMalzemeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MusteriFirmaId");

                    b.HasIndex("MusteriMalzemeId");

                    b.HasIndex("TedarikciFirmaId");

                    b.HasIndex("TedarikciMalzemeId");

                    b.ToTable("TedarikciMalzemeEslestirmeleri");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.Firma", "Firma")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("FirmaId");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Dokuman", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "YukleyenUser")
                        .WithMany()
                        .HasForeignKey("YukleyenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("YukleyenUser");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Firma", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.FirmaIliskisi", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Firma", "MusteriFirma")
                        .WithMany("MusteriOlarakIliskiler")
                        .HasForeignKey("MusteriFirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Firma", "TedarikciFirma")
                        .WithMany("TedarikciOlarakIliskiler")
                        .HasForeignKey("TedarikciFirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MusteriFirma");

                    b.Navigation("TedarikciFirma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Ihale", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Firma", "MusteriFirma")
                        .WithMany("Ihaleler")
                        .HasForeignKey("MusteriFirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MusteriFirma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleDaveti", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Ihale", "Ihale")
                        .WithMany("Davetler")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Firma", "TedarikciFirma")
                        .WithMany()
                        .HasForeignKey("TedarikciFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Ihale");

                    b.Navigation("TedarikciFirma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleDokuman", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.Ihale", "Ihale")
                        .WithMany("Dokumanlar")
                        .HasForeignKey("IhaleId");

                    b.HasOne("VendorPortal.Models.Entities.IhaleTeklif", "IhaleTeklif")
                        .WithMany()
                        .HasForeignKey("IhaleTeklifId");

                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "YukleyenUser")
                        .WithMany()
                        .HasForeignKey("YukleyenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ihale");

                    b.Navigation("IhaleTeklif");

                    b.Navigation("YukleyenUser");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleKalem", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Ihale", "Ihale")
                        .WithMany("Kalemler")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Malzeme", "Malzeme")
                        .WithMany("IhaleKalemleri")
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Ihale");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleTeklif", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Ihale", "Ihale")
                        .WithMany("Teklifler")
                        .HasForeignKey("IhaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Firma", "TedarikciFirma")
                        .WithMany()
                        .HasForeignKey("TedarikciFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Ihale");

                    b.Navigation("TedarikciFirma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleTeklifKalem", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.IhaleKalem", "IhaleKalem")
                        .WithMany("TeklifKalemleri")
                        .HasForeignKey("IhaleKalemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.IhaleTeklif", "IhaleTeklif")
                        .WithMany("TeklifKalemleri")
                        .HasForeignKey("IhaleTeklifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("IhaleKalem");

                    b.Navigation("IhaleTeklif");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Malzeme", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Firma", "Firma")
                        .WithMany("Malzemeler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisBaslik", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Firma", "MusteriFirma")
                        .WithMany("MusteriOlarakSiparisler")
                        .HasForeignKey("MusteriFirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Firma", "TedarikciFirma")
                        .WithMany("TedarikciOlarakSiparisler")
                        .HasForeignKey("TedarikciFirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("MusteriFirma");

                    b.Navigation("TedarikciFirma");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisKalem", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VendorPortal.Models.Entities.Malzeme", "Malzeme")
                        .WithMany("SiparisKalemleri")
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.SiparisBaslik", "SiparisBaslik")
                        .WithMany("Kalemler")
                        .HasForeignKey("SiparisBaslikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Malzeme");

                    b.Navigation("SiparisBaslik");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisOnayGecmisi", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "IslemYapanUser")
                        .WithMany()
                        .HasForeignKey("IslemYapanUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.SiparisBaslik", "SiparisBaslik")
                        .WithMany("OnayGecmisleri")
                        .HasForeignKey("SiparisBaslikId");

                    b.HasOne("VendorPortal.Models.Entities.SiparisKalem", "SiparisKalem")
                        .WithMany("OnayGecmisleri")
                        .HasForeignKey("SiparisKalemId");

                    b.Navigation("IslemYapanUser");

                    b.Navigation("SiparisBaslik");

                    b.Navigation("SiparisKalem");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.TedarikciMalzemeEslestirme", b =>
                {
                    b.HasOne("VendorPortal.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("VendorPortal.Models.Entities.Firma", "MusteriFirma")
                        .WithMany()
                        .HasForeignKey("MusteriFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Malzeme", "MusteriMalzeme")
                        .WithMany("MusteriEslestirmeleri")
                        .HasForeignKey("MusteriMalzemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Firma", "TedarikciFirma")
                        .WithMany()
                        .HasForeignKey("TedarikciFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendorPortal.Models.Entities.Malzeme", "TedarikciMalzeme")
                        .WithMany("TedarikciEslestirmeleri")
                        .HasForeignKey("TedarikciMalzemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MusteriFirma");

                    b.Navigation("MusteriMalzeme");

                    b.Navigation("TedarikciFirma");

                    b.Navigation("TedarikciMalzeme");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Firma", b =>
                {
                    b.Navigation("Ihaleler");

                    b.Navigation("Kullanicilar");

                    b.Navigation("Malzemeler");

                    b.Navigation("MusteriOlarakIliskiler");

                    b.Navigation("MusteriOlarakSiparisler");

                    b.Navigation("TedarikciOlarakIliskiler");

                    b.Navigation("TedarikciOlarakSiparisler");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Ihale", b =>
                {
                    b.Navigation("Davetler");

                    b.Navigation("Dokumanlar");

                    b.Navigation("Kalemler");

                    b.Navigation("Teklifler");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleKalem", b =>
                {
                    b.Navigation("TeklifKalemleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.IhaleTeklif", b =>
                {
                    b.Navigation("TeklifKalemleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.Malzeme", b =>
                {
                    b.Navigation("IhaleKalemleri");

                    b.Navigation("MusteriEslestirmeleri");

                    b.Navigation("SiparisKalemleri");

                    b.Navigation("TedarikciEslestirmeleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisBaslik", b =>
                {
                    b.Navigation("Kalemler");

                    b.Navigation("OnayGecmisleri");
                });

            modelBuilder.Entity("VendorPortal.Models.Entities.SiparisKalem", b =>
                {
                    b.Navigation("OnayGecmisleri");
                });
#pragma warning restore 612, 618
        }
    }
}
